# Generated by Django 3.1.7 on 2021-02-28 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergy',
            table='allergies',
        ),
    ]
