# Generated by Django 3.1.7 on 2021-02-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210228_0230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allery_Drink',
            new_name='Allergy_Drink',
        ),
    ]
